version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    image: indo_sixmursc
    container_name: indo_sixmursc
    external_links:
      - dev_mysql:mysql
    networks:
      - default
    # ports:
    #   - "8000:80"
    #   - "8443:443"
    #   - "10022:22"
    volumes:
      - storage:/storage
      - ../_htdocs/indo_sixmursc/:/app/
      - ./:/docker/
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml
    environment:
      VIRTUAL_HOST: "sixmurs.local.vm,mursmedic.local.vm,sixmurs-id.local.vm,sixmurs-sg.local.vm,sixmurs-my.local.vm,sixmurs-ph.local.vm,sixmurs-th.local.vm,sixmurs-vn.local.vm,sixmurs-vn.local.vm,tarafis.local.vm,mursmedic-sixmurs-ph.local.vm"
      VIRTUAL_PORT: "80"
      # PHP_XDEBUG_ENABLED: 1
      # PHP_IDE_CONFIG: serverName=local.vm
      # XDEBUG_CONFIG: remote_host=172.18.0.1 remote_connect_back=1

#######################################
# Storage
#######################################
volumes:
  storage:
    driver: local
    driver_opts:
      device: /home/vt745/Documents/dc_indo_sixmursc/backup
      o: bind

networks:
  default:
    external:
      name: dev
